### PR TITLE
selector-no-redundant-nesting-selector: fix false positives, fixes #32

### LINKED ISSUE #32: selector-no-redundant-nesting-selector false positive when followed by a character other than ':'
'selector-no-redundant-nesting-selector' rule falsely assumes the selector is redundant in this common BEM use case:

```
.block {
  &__element {
    ...
  }
  &--modifier {
   ...
  }
}
```

More generally nesting selector is not redundant if immediately followed by a non white space character as it results in a new not nested rule.

### PR DESCRIPTION
**Pull request by kristerkari**
Fix false positives when `&` is used to combine classname from multiple parts or when BEM syntax is used.

### CODE REVIEW

**Comment by dryoma** [comment]
By the way, congratulations with the first bug filed and fixed! :)

File: src/rules/selector-no-redundant-nesting-selector/__tests__/index.js [hunk 1]
```diff
@@ -137,6 +160,53 @@ testRule(rule, {
...
+        & ~ .foo {}
+      }
+    `,
+    line: 3,
+    message: messages.rejected,
+    description: "when an ampersand precedes a sibling operator",
+  }, {
+    code: `
       p {
         &  .class {}
```
Comment (dryoma) [inline src/rules/selector-no-redundant-nesting-selector/__tests__/index.js]: `&  #class {}`, `&  %class {}`, `&  &-class {}` — these will not return errors.

Comment (kristerkari) [inline src/rules/selector-no-redundant-nesting-selector/__tests__/index.js]: ah, true! Need to add tests for those too.

Comment (dryoma) [inline src/rules/selector-no-redundant-nesting-selector/__tests__/index.js]: I pulled a fix for that: #40 If nothing is left out, you can merge it and publish a patch (as per a suggestion in #38

Comment (kristerkari) [inline src/rules/selector-no-redundant-nesting-selector/__tests__/index.js]: Alright, I'll do a patch release now.
