### PR TITLE
Handle interpolation in selector-nest-combinators

### LINKED ISSUE #306: false positive 'selector-nest-combinators'
Given a value 'always' and a stylesheet:

```
.class-name {
	#{if(&, "&", "")} {

	}	
}
```

The linter will report the error:

`'Expected combinator "}" of type "tag" to be in a nested form'`

### PR DESCRIPTION
**Pull request by kristerkari**
Fixes #306

### CODE REVIEW

File: src/rules/selector-nest-combinators/index.js [hunk 1]
```diff
@@ -20,21 +21,39 @@ export default function(expectation) {
...
+    const chainingTypes = [
+      "attribute",
+      "class",
+      "id",
+      "pseudo",
+      "tag",
+      "universal"
+    ];
+
+    const interpolationRe = /#{.+}$/;
```
Comment (lxsymington) [inline src/rules/selector-nest-combinators/index.js]: Given that this is checking for the presence of any interpolation in the current selector, it's probably not particularly relevant, but it would generallly be better to use the non-greedy + operator? So that it would not match `#{$var} .selector li #{$var-2}`. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#quantifiers
